### ISSUE TITLE
Add notice in admin for pending hub transfers

### ISSUE THREAD

**Issue by ProAviaAZ** [PaintSplasher/phpvms7_SPTransfer#3]
Enhancement

Add notice of pending hub transfer requests to the admin panel.
Maybe add an area directly below pending pilots and pireps to show pending hub transfers. Use similar logic as existing pending pilots/pireps.

![image](https://github.com/user-attachments/assets/c83061ac-4965-4b6f-8032-6fb3c701f699)

While I was able to get the info box to display, I haven't determined how to display if any transfers are pending.

Additionally - in Dispo Theme - move user dashboard "Hub Transfer" to the right under username, as this is a user function.

![image](https://github.com/user-attachments/assets/e054b1e4-1ea6-4125-a7fa-bb33f5cb18bd)

**Comment by PaintSplasher** [comment]
* Widget added

https://github.com/PaintSplasher/phpvms7_SPTransfer/commit/459d009f6be248852208f5ff2178c33ad30cf89a
