### ISSUE TITLE
The amount the pilot gets charged for every request

### ISSUE THREAD

**Issue by ProAviaAZ** [PaintSplasher/phpvms7_SPTransfer#4]
It appears that the pilot presently gets charge for every request - whether the request is approved or denied.
It may be better to only charge if the request is approved. 
Alternately, change the wording "You get charged with $xxx.xx for every transfer." to denote that the charge pertains whether the request is approve or denied.

**Comment by PaintSplasher** [comment]
- Charge type added.
- Better wording.

https://github.com/PaintSplasher/phpvms7_SPTransfer/commit/37d377261b4e95dc446553b7498efeb3b542618c
